export const APP_DEFAULTS = {
  wsUrl: 'ws://127.0.0.1:9002',
  channel: 'can0',
  scanTimeoutMs: '500',
};

export const DEV_SERVER = {
  host: '0.0.0.0',
  port: Number.parseInt(import.meta?.env?.VITE_FACTORY_UI_PORT || '18110', 10) || 18110,
};

export const CMD_TIMEOUTS = {
  shortMs: 1500,
  controlMs: 6000,
  stateMs: 1500,
  verifyMs: 8000,
  setIdMs: 12000,
  registerMs: 3000,
  storeMs: 4000,
};

export const DAMIAO_ARM_PARAM_DEFS = [
  {
    key: 'ctrlMode',
    rid: 10,
    variable: 'CTRL_MODE',
    label: 'CTRL_MODE',
    labelKey: 'damiao_param_ctrl_mode',
    descKey: 'damiao_param_ctrl_mode_desc',
    dataType: 'u32',
    range: '[1, 4]',
    writable: true,
    common: true,
    group: 'core',
    defaultValue: '2',
  },
  {
    key: 'currentBw',
    rid: 24,
    variable: 'I_BW',
    label: 'I_BW',
    labelKey: 'damiao_param_i_bw',
    descKey: 'damiao_param_i_bw_desc',
    dataType: 'f32',
    range: '[100.0, 10000.0]',
    writable: true,
    common: true,
    group: 'core',
    defaultValue: '1000',
  },
  {
    key: 'velKp',
    rid: 25,
    variable: 'KP_ASR',
    label: 'KP_ASR',
    labelKey: 'damiao_param_kp_asr',
    descKey: 'damiao_param_kp_asr_desc',
    dataType: 'f32',
    range: '[0.0, 3.4E38]',
    writable: true,
    common: true,
    group: 'core',
    defaultValue: '0',
  },
  {
    key: 'velKi',
    rid: 26,
    variable: 'KI_ASR',
    label: 'KI_ASR',
    labelKey: 'damiao_param_ki_asr',
    descKey: 'damiao_param_ki_asr_desc',
    dataType: 'f32',
    range: '[0.0, 3.4E38]',
    writable: true,
    common: true,
    group: 'core',
    defaultValue: '0',
  },
  {
    key: 'posKp',
    rid: 27,
    variable: 'KP_APR',
    label: 'KP_APR',
    labelKey: 'damiao_param_kp_apr',
    descKey: 'damiao_param_kp_apr_desc',
    dataType: 'f32',
    range: '[0.0, 3.4E38]',
    writable: true,
    common: true,
    group: 'core',
    defaultValue: '0',
  },
  {
    key: 'posKi',
    rid: 28,
    variable: 'KI_APR',
    label: 'KI_APR',
    labelKey: 'damiao_param_ki_apr',
    descKey: 'damiao_param_ki_apr_desc',
    dataType: 'f32',
    range: '[0.0, 3.4E38]',
    writable: true,
    common: true,
    group: 'core',
    defaultValue: '0',
  },
  {
    key: 'uvValue',
    rid: 0,
    variable: 'UV_Value',
    label: 'UV_Value',
    labelKey: 'damiao_param_uv_value',
    descKey: 'damiao_param_uv_value_desc',
    dataType: 'f32',
    range: '(10.0, 3.4E38]',
    writable: true,
    common: true,
    group: 'limits',
    defaultValue: '',
  },
  {
    key: 'otValue',
    rid: 2,
    variable: 'OT_Value',
    label: 'OT_Value',
    labelKey: 'damiao_param_ot_value',
    descKey: 'damiao_param_ot_value_desc',
    dataType: 'f32',
    range: '[80.0, 200)',
    writable: true,
    common: true,
    group: 'limits',
    defaultValue: '',
  },
  {
    key: 'ocValue',
    rid: 3,
    variable: 'OC_Value',
    label: 'OC_Value',
    labelKey: 'damiao_param_oc_value',
    descKey: 'damiao_param_oc_value_desc',
    dataType: 'f32',
    range: '(0.0, 1.0)',
    writable: true,
    common: true,
    group: 'limits',
    defaultValue: '',
  },
  {
    key: 'maxSpd',
    rid: 6,
    variable: 'MAX_SPD',
    label: 'MAX_SPD',
    labelKey: 'damiao_param_max_spd',
    descKey: 'damiao_param_max_spd_desc',
    dataType: 'f32',
    range: '(0.0, 3.4E38]',
    writable: true,
    common: true,
    group: 'limits',
    defaultValue: '',
  },
  {
    key: 'pmax',
    rid: 21,
    variable: 'PMAX',
    label: 'PMAX',
    labelKey: 'damiao_param_pmax',
    descKey: 'damiao_param_pmax_desc',
    dataType: 'f32',
    range: '(0.0, 3.4E38]',
    writable: true,
    common: true,
    group: 'limits',
    defaultValue: '',
  },
  {
    key: 'vmax',
    rid: 22,
    variable: 'VMAX',
    label: 'VMAX',
    labelKey: 'damiao_param_vmax',
    descKey: 'damiao_param_vmax_desc',
    dataType: 'f32',
    range: '(0.0, 3.4E38]',
    writable: true,
    common: true,
    group: 'limits',
    defaultValue: '',
  },
  {
    key: 'tmax',
    rid: 23,
    variable: 'TMAX',
    label: 'TMAX',
    labelKey: 'damiao_param_tmax',
    descKey: 'damiao_param_tmax_desc',
    dataType: 'f32',
    range: '(0.0, 3.4E38]',
    writable: true,
    common: true,
    group: 'limits',
    defaultValue: '',
  },
  {
    key: 'mstId',
    rid: 7,
    variable: 'MST_ID',
    label: 'MST_ID',
    labelKey: 'damiao_param_mst_id',
    descKey: 'damiao_param_mst_id_desc',
    dataType: 'u32',
    range: '[0, 0x7FF]',
    writable: true,
    common: true,
    group: 'identity',
    risky: true,
    defaultValue: '',
  },
  {
    key: 'escId',
    rid: 8,
    variable: 'ESC_ID',
    label: 'ESC_ID',
    labelKey: 'damiao_param_esc_id',
    descKey: 'damiao_param_esc_id_desc',
    dataType: 'u32',
    range: '[0, 0x7FF]',
    writable: true,
    common: true,
    group: 'identity',
    risky: true,
    defaultValue: '',
  },
  {
    key: 'timeout',
    rid: 9,
    variable: 'TIMEOUT',
    label: 'TIMEOUT',
    labelKey: 'damiao_param_timeout',
    descKey: 'damiao_param_timeout_desc',
    dataType: 'u32',
    range: '[0, 2^32-1]',
    writable: true,
    common: true,
    group: 'identity',
    risky: true,
    defaultValue: '',
  },
  {
    key: 'canBr',
    rid: 35,
    variable: 'can_br',
    label: 'can_br',
    labelKey: 'damiao_param_can_br',
    descKey: 'damiao_param_can_br_desc',
    dataType: 'u32',
    range: '[0, 4]',
    writable: true,
    common: true,
    group: 'identity',
    risky: true,
    defaultValue: '',
  },
  {
    key: 'acc',
    rid: 4,
    variable: 'ACC',
    label: 'ACC',
    dataType: 'f32',
    range: '(0.0, 3.4E38)',
    writable: true,
    common: false,
    group: 'advanced',
    defaultValue: '',
  },
  {
    key: 'dec',
    rid: 5,
    variable: 'DEC',
    label: 'DEC',
    dataType: 'f32',
    range: '[-3.4E38, 0.0)',
    writable: true,
    common: false,
    group: 'advanced',
    defaultValue: '',
  },
  {
    key: 'ovValue',
    rid: 29,
    variable: 'OV_Value',
    label: 'OV_Value',
    dataType: 'f32',
    range: 'TBD',
    writable: true,
    common: false,
    group: 'advanced',
    defaultValue: '',
  },
  {
    key: 'gref',
    rid: 30,
    variable: 'GREF',
    label: 'GREF',
    dataType: 'f32',
    range: '(0.0, 1.0]',
    writable: true,
    common: false,
    group: 'advanced',
    defaultValue: '',
  },
  {
    key: 'deta',
    rid: 31,
    variable: 'Deta',
    label: 'Deta',
    dataType: 'f32',
    range: '[1.0, 30.0]',
    writable: true,
    common: false,
    group: 'advanced',
    defaultValue: '',
  },
  {
    key: 'vBw',
    rid: 32,
    variable: 'V_BW',
    label: 'V_BW',
    dataType: 'f32',
    range: '(0.0, 500.0)',
    writable: true,
    common: false,
    group: 'advanced',
    defaultValue: '',
  },
  {
    key: 'iqC1',
    rid: 33,
    variable: 'IQ_c1',
    label: 'IQ_c1',
    dataType: 'f32',
    range: '[100.0, 10000.0]',
    writable: true,
    common: false,
    group: 'advanced',
    defaultValue: '',
  },
  {
    key: 'vlC1',
    rid: 34,
    variable: 'VL_c1',
    label: 'VL_c1',
    dataType: 'f32',
    range: '(0.0, 10000.0]',
    writable: true,
    common: false,
    group: 'advanced',
    defaultValue: '',
  },
];

export const DAMIAO_CTRL_PARAM_RID = Object.freeze(
  Object.fromEntries(
    DAMIAO_ARM_PARAM_DEFS.slice(0, 6).map((item) => [item.key, item.rid]),
  ),
);

export const DAMIAO_RW_REGISTER_DEFS = [
  { rid: 0, variable: 'UV_Value', dataType: 'f32', range: '(10.0, 3.4E38]', common: true },
  { rid: 1, variable: 'KT_Value', dataType: 'f32', range: '[0.0, 3.4E38]', common: false },
  { rid: 2, variable: 'OT_Value', dataType: 'f32', range: '[80.0, 200)', common: true },
  { rid: 3, variable: 'OC_Value', dataType: 'f32', range: '(0.0, 1.0)', common: true },
  { rid: 4, variable: 'ACC', dataType: 'f32', range: '(0.0, 3.4E38)', common: false },
  { rid: 5, variable: 'DEC', dataType: 'f32', range: '[-3.4E38, 0.0)', common: false },
  { rid: 6, variable: 'MAX_SPD', dataType: 'f32', range: '(0.0, 3.4E38]', common: true },
  { rid: 7, variable: 'MST_ID', dataType: 'u32', range: '[0, 0x7FF]', common: true },
  { rid: 8, variable: 'ESC_ID', dataType: 'u32', range: '[0, 0x7FF]', common: true },
  { rid: 9, variable: 'TIMEOUT', dataType: 'u32', range: '[0, 2^32-1]', common: true },
  { rid: 10, variable: 'CTRL_MODE', dataType: 'u32', range: '[1, 4]', common: true },
  { rid: 21, variable: 'PMAX', dataType: 'f32', range: '(0.0, 3.4E38]', common: true },
  { rid: 22, variable: 'VMAX', dataType: 'f32', range: '(0.0, 3.4E38]', common: true },
  { rid: 23, variable: 'TMAX', dataType: 'f32', range: '(0.0, 3.4E38]', common: true },
  { rid: 24, variable: 'I_BW', dataType: 'f32', range: '[100.0, 10000.0]', common: true },
  { rid: 25, variable: 'KP_ASR', dataType: 'f32', range: '[0.0, 3.4E38]', common: true },
  { rid: 26, variable: 'KI_ASR', dataType: 'f32', range: '[0.0, 3.4E38]', common: true },
  { rid: 27, variable: 'KP_APR', dataType: 'f32', range: '[0.0, 3.4E38]', common: true },
  { rid: 28, variable: 'KI_APR', dataType: 'f32', range: '[0.0, 3.4E38]', common: true },
  { rid: 29, variable: 'OV_Value', dataType: 'f32', range: 'TBD', common: false },
  { rid: 30, variable: 'GREF', dataType: 'f32', range: '(0.0, 1.0]', common: false },
  { rid: 31, variable: 'Deta', dataType: 'f32', range: '[1.0, 30.0]', common: false },
  { rid: 32, variable: 'V_BW', dataType: 'f32', range: '(0.0, 500.0)', common: false },
  { rid: 33, variable: 'IQ_c1', dataType: 'f32', range: '[100.0, 10000.0]', common: false },
  { rid: 34, variable: 'VL_c1', dataType: 'f32', range: '(0.0, 10000.0]', common: false },
  { rid: 35, variable: 'can_br', dataType: 'u32', range: '[0, 4]', common: true },
];

function normalizeDamiaoSnapshotField(variable) {
  return String(variable || '')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();
}

const DAMIAO_REGISTER_SNAPSHOT_FIELD_OVERRIDES = Object.freeze({
  7: 'register_mst_id',
  8: 'register_esc_id',
});

export const DAMIAO_REGISTER_SNAPSHOT_FIELDS = Object.freeze(
  Object.fromEntries(
    DAMIAO_RW_REGISTER_DEFS.map((def) => [
      def.rid,
      DAMIAO_REGISTER_SNAPSHOT_FIELD_OVERRIDES[def.rid] || normalizeDamiaoSnapshotField(def.variable),
    ]),
  ),
);
